---
title: "Create hexagonal global grid"
author: "Ate Poorthuis"
date: "02/09/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(sf)
```

## Create hexagonal global grid

We start by reading in country-level data from Natural Earth. The end-goal is to create a global hexagonal grid with cells of 200km. Cells should be neatly clipped to the land boundaries.

```{r}
countries <- read_sf(here("analysis/data/raw_data/ne_50m_admin_0_countries/")) %>% 
  st_transform(CRS("+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"))
plot(st_geometry(countries))
```

```{r}
hexagons <- countries %>% 
  st_buffer(400000) %>% 
  st_make_grid(cellsize = 200000, square = F) %>% 
  st_sf() %>% 
  rowid_to_column("hex")

hexagons_clipped <- countries %>% 
  st_buffer(100) %>% 
  st_intersection(hexagons) %>% 
  select(hex)

plot(st_geometry(hexagons_clipped))
```

The resulting grids are saved in `analysis/data/derived/data`.

```{r}
write_sf(hexagons_clipped, here("analysis/data/derived_data/global_hex_grid.geojson"))
saveRDS(hexagons_clipped, here("analysis/data/derived_data/global_hex_grid.rds"))
```

